import enum

class SourceType(str, enum.Enum):
    PATIENT = "PATIENT"
    CAREGIVER = "CAREGIVER"
    DOCTOR = "DOCTOR"
    MEDICAL_RECORD = "MEDICAL_RECORD"
    MEDICATION_RECORD = "MEDICATION_RECORD"
    LAB_RECORD = "LAB_RECORD"
    SYSTEM = "SYSTEM"
    AI_DERIVED = "AI_DERIVED"
    AI_CLINICAL_CONSIDERATION = "AI_CLINICAL_CONSIDERATION"

class InformationState(str, enum.Enum):
    OBSERVED = "OBSERVED"
    CLINICIAN_CONFIRMED = "CLINICIAN_CONFIRMED"
    HISTORICAL = "HISTORICAL"
    AI_DERIVED = "AI_DERIVED"
    AI_CLINICAL_CONSIDERATION = "AI_CLINICAL_CONSIDERATION"
    OUTDATED = "OUTDATED"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"

class EvidenceStatus(str, enum.Enum):
    IMMUTABLE = "IMMUTABLE"
    ARCHIVED = "ARCHIVED"

class ConflictStatus(str, enum.Enum):
    CONFLICTING = "CONFLICTING"
    REQUIRES_CLINICIAN_REVIEW = "REQUIRES_CLINICIAN_REVIEW"
    RESOLVED = "RESOLVED"

class PageType(str, enum.Enum):
    PATIENT = "PATIENT"
    CLINICAL = "CLINICAL"
    CAREGIVER = "CAREGIVER"
    DERIVED = "DERIVED"
