import logging
from typing import Dict, Any, Optional
from app.services.llm.provider import LLMProvider, LLMResult, MockLLMProvider
from app.services.llm.schemas import LLMStatus, ProcessingMethod
from app.services.llm.gemini_provider import GeminiProvider
from app.services.llm.groq_provider import GroqProvider

import hashlib
import time

logger = logging.getLogger(__name__)


class ResilientLLMProvider(LLMProvider):
    """
    Multi-Tier Resilient LLM Provider with automatic failover & quota conservation:
      - 15-minute in-memory response cache (0 API calls for repeat clinical queries)
      - Tier 1: Google Gemini Flash (gemini-3.6-flash) with 429 cool-down circuit breaker
      - Tier 2: Groq (Primary: openai/gpt-oss-120b -> Fallback: openai/gpt-oss-20b)
      - Tier 3: Deterministic Clinical Rule Engine (MockLLMProvider)
    """

    # In-memory query cache: {hash_key: (timestamp, result_dict)}
    _reasoning_cache: Dict[str, tuple[float, Dict[str, Any]]] = {}
    CACHE_TTL_SECONDS: int = 900  # 15 minutes

    def __init__(
        self,
        gemini_provider: Optional[GeminiProvider] = None,
        groq_provider: Optional[GroqProvider] = None,
        mock_provider: Optional[MockLLMProvider] = None
    ):
        self.gemini = gemini_provider or GeminiProvider()
        self.groq = groq_provider or GroqProvider()
        self.mock = mock_provider or MockLLMProvider()

    def extract_observation(self, text: str, patient_context: Optional[Dict[str, Any]] = None) -> LLMResult:
        # Tier 1: Gemini Flash
        if self.gemini.is_configured():
            try:
                res = self.gemini.extract_observation(text, patient_context)
                if res.status == LLMStatus.SUCCESS:
                    logger.info("Observation extraction successfully handled by Tier 1 (Gemini Flash).")
                    return res
                logger.warning(f"Tier 1 (Gemini) returned non-success status ({res.status}: {res.error_message}). Failing over to Groq...")
            except Exception as e:
                logger.warning(f"Tier 1 (Gemini) raised exception ({e}). Failing over to Tier 2 (Groq)...")

        # Tier 2: Groq
        if self.groq.is_configured():
            try:
                res = self.groq.extract_observation(text, patient_context)
                if res.status == LLMStatus.SUCCESS:
                    logger.info("Observation extraction successfully handled by Tier 2 (Groq).")
                    return res
                logger.warning(f"Tier 2 (Groq) returned non-success status ({res.status}: {res.error_message}). Failing over to Deterministic Engine...")
            except Exception as e:
                logger.warning(f"Tier 2 (Groq) raised exception ({e}). Failing over to Tier 3 (Deterministic Engine)...")

        # Tier 3: Deterministic Fallback Engine
        logger.info("Falling back to Tier 3 (Deterministic Parser) for observation extraction.")
        return LLMResult(
            status=LLMStatus.LLM_UNAVAILABLE,
            error_message="Neither Gemini nor Groq API keys are configured, falling back to deterministic extraction.",
            processing_method=ProcessingMethod.LLM_FALLBACK
        )

    def generate_clinical_reasoning(self, question: str, patient_context: Dict[str, Any]) -> Dict[str, Any]:
        # Check in-memory query cache first (0 API quota used)
        pcode = patient_context.get("patient", {}).get("patient_code", "P001") if isinstance(patient_context, dict) else "P001"
        cache_key = hashlib.md5(f"{pcode}:{question.strip().lower()}".encode()).hexdigest()
        now = time.time()

        if cache_key in self._reasoning_cache:
            ts, cached_data = self._reasoning_cache[cache_key]
            if now - ts < self.CACHE_TTL_SECONDS:
                logger.info("Serving clinical reasoning from cache (0 free-tier tokens consumed).")
                res = dict(cached_data)
                res["_from_cache"] = True
                return res

        last_errors = []

        # Tier 1: Gemini Flash
        if self.gemini.is_configured():
            try:
                logger.info("Attempting Tier 1 (Google Gemini Flash) for clinical reasoning...")
                reasoning = self.gemini.generate_clinical_reasoning(question, patient_context)
                if reasoning and isinstance(reasoning, dict) and "considerations" in reasoning:
                    logger.info("Clinical reasoning successfully generated by Tier 1 (Gemini Flash).")
                    self._reasoning_cache[cache_key] = (now, reasoning)
                    return reasoning
                logger.warning("Tier 1 (Gemini) returned invalid schema; failing over to Tier 2...")
            except Exception as e:
                err_msg = f"Gemini Flash failed ({type(e).__name__}: {str(e)})"
                logger.warning(f"{err_msg}. Failing over to Tier 2 (Groq)...")
                last_errors.append(err_msg)

        # Tier 2: Groq (Primary: openai/gpt-oss-120b -> Fallback: openai/gpt-oss-20b)
        if self.groq.is_configured():
            try:
                logger.info("Attempting Tier 2 (Groq openai/gpt-oss-120b -> openai/gpt-oss-20b) for clinical reasoning...")
                reasoning = self.groq.generate_clinical_reasoning(question, patient_context)
                if reasoning and isinstance(reasoning, dict) and "considerations" in reasoning:
                    logger.info("Clinical reasoning successfully generated by Tier 2 (Groq).")
                    self._reasoning_cache[cache_key] = (now, reasoning)
                    return reasoning
                logger.warning("Tier 2 (Groq) returned invalid schema; failing over to Tier 3...")
            except Exception as e:
                err_msg = f"Groq failed ({type(e).__name__}: {str(e)})"
                logger.warning(f"{err_msg}. Failing over to Tier 3 (Deterministic Engine)...")
                last_errors.append(err_msg)

        # Tier 3: Deterministic Clinical Rule Engine
        logger.info("Serving clinical reasoning from Tier 3 (Deterministic Offline Engine).")
        result = self.mock.generate_clinical_reasoning(question, patient_context)
        if last_errors:
            result["_fallback_notice"] = f"Live free-tier APIs transitioned to offline engine: {'; '.join(last_errors)}"
        else:
            result["_fallback_notice"] = "Running on offline deterministic clinical engine (No external API key set)."
        result["_llm_model_used"] = "EvoCare Deterministic Clinical Engine (Fallback)"
        return result

    def generate_patient_response(self, question: str, patient_context: Dict[str, Any]) -> str:
        """
        Generates an empathetic, plain-language response tailored for the patient.
        Tiers:
          1. Gemini Flash
          2. Groq (gpt-oss-120b / gpt-oss-20b)
          3. Deterministic Fallback Answer
        """
        pcode = patient_context.get("patient", {}).get("patient_code", "P001") if isinstance(patient_context, dict) else "P001"
        cache_key = hashlib.md5(f"patient:{pcode}:{question.strip().lower()}".encode()).hexdigest()
        now = time.time()

        if cache_key in self._reasoning_cache:
            ts, cached_data = self._reasoning_cache[cache_key]
            if now - ts < self.CACHE_TTL_SECONDS and isinstance(cached_data, dict) and "text" in cached_data:
                logger.info("Serving patient companion response from cache.")
                return cached_data["text"]

        patient_name = patient_context.get("patient", {}).get("name", "Meenakshi Raman") if isinstance(patient_context, dict) else "Meenakshi Raman"
        meds = patient_context.get("medications", []) if isinstance(patient_context, dict) else []
        med_summary = "\n".join([f"- **{m.get('name', 'Medication')}** {m.get('dose', '')} ({m.get('frequency', '')}): {m.get('indication', '')} • Instructions: {m.get('instructions', 'Take as directed')}" for m in meds]) if meds else "None recorded."
        
        diagnoses = patient_context.get("diagnoses", []) if isinstance(patient_context, dict) else []
        diag_summary = "\n".join([f"- **{d.get('condition', '')}** ({d.get('icd_code', '')}): {d.get('status', '')}" for d in diagnoses]) if diagnoses else "Type 2 Diabetes, Hypertension, Bilateral Knee Osteoarthritis."

        recent_obs = patient_context.get("recent_observations", []) if isinstance(patient_context, dict) else []
        obs_summary = "\n".join([f"- {o.get('observed_at', '')[:10]}: {o.get('statement', '')}" for o in recent_obs[:6]]) if recent_obs else "Daily routines monitored normally."

        wiki_notes = patient_context.get("wiki_markdown_context", "") if isinstance(patient_context, dict) else ""

        prompt = f"""
You are the personal EvoCare Health Companion for {patient_name}.
{patient_name} has asked: "{question}"

Patient Health Record Context:
Confirmed Conditions:
{diag_summary}

Active Medications:
{med_summary}

Recent Observations & Doctor Notes:
{obs_summary}
{wiki_notes[:800]}

Instructions:
1. Provide a warm, clear, empathetic answer directly addressing {patient_name}'s question.
2. Ground your facts strictly in the medical record and medication schedule above.
3. Speak in plain, encouraging English. Use bullet points for easy reading.
4. Reminder: This is for information only; remind {patient_name} to check with Dr. Ramesh Varma for any changes or clinical advice.
"""

        system_prompt = f"You are a friendly, compassionate healthcare companion for {patient_name}. You explain their health records in simple, reassuring words."

        # Tier 1: Gemini Flash
        if self.gemini.is_configured() and not self.gemini.is_rate_limited():
            try:
                from google import genai
                from google.genai import types
                client = genai.Client(api_key=self.gemini.api_key)
                resp = client.models.generate_content(
                    model=self.gemini.model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=system_prompt,
                        temperature=0.2,
                        max_output_tokens=1000
                    )
                )
                ans = resp.text.strip()
                if ans:
                    self._reasoning_cache[cache_key] = (now, {"text": ans})
                    return ans
            except Exception as e:
                logger.warning(f"Gemini failed for patient companion ({e}), failing over to Groq...")

        # Tier 2: Groq
        if self.groq.is_configured():
            try:
                from groq import Groq
                client = Groq(api_key=self.groq.api_key)
                raw_text, _ = self.groq._call_groq_completion(client, prompt, system_prompt)
                if raw_text:
                    self._reasoning_cache[cache_key] = (now, {"text": raw_text.strip()})
                    return raw_text.strip()
            except Exception as e:
                logger.warning(f"Groq failed for patient companion ({e}), falling back to deterministic answer...")

        # Tier 3: Deterministic Fallback Answer
        fallback_ans = self._generate_fallback_patient_answer(question, patient_name, meds, diagnoses, recent_obs)
        self._reasoning_cache[cache_key] = (now, {"text": fallback_ans})
        return fallback_ans

    def _generate_fallback_patient_answer(
        self,
        question: str,
        patient_name: str,
        meds: list,
        diagnoses: list,
        recent_obs: list
    ) -> str:
        q_lower = question.lower()

        if any(w in q_lower for w in ["medication", "medicine", "pill", "tablet", "dose", "when"]):
            med_lines = []
            if meds:
                for m in meds:
                    med_lines.append(f"• **{m.get('name')}** ({m.get('dose')}): {m.get('frequency')}. Timing: {m.get('indication', 'As prescribed')}")
            else:
                med_lines = [
                    "• **Metformin (500 mg)**: Twice daily with morning and evening meals.",
                    "• **Amlodipine (5 mg)**: Once daily in the morning.",
                    "• **Atorvastatin (10 mg)**: Once nightly at bedtime.",
                    "• **Paracetamol (500 mg)**: As needed for knee pain (maximum 2 grams/day)."
                ]
            return (
                f"Hello {patient_name.split()[0]}. Here is your current daily medication schedule as documented by your care team:\n\n"
                + "\n".join(med_lines)
                + "\n\n💡 **Tip**: Taking your medications with water at the same scheduled times helps maintain steady health. If you feel dizzy or notice any side effects, please reach out to your doctor or caregiver."
            )

        if any(w in q_lower for w in ["dizzy", "dizziness", "balance", "fall", "walking", "stand"]):
            return (
                f"Hello {patient_name.split()[0]}.\n\n"
                "According to your recent care notes, you have experienced light morning dizziness and occasional unsteadiness when getting out of bed. Here are some helpful safety reminders from your records:\n\n"
                "• **Pause Before Standing**: Sit upright on the edge of your bed for 30–60 seconds before standing up to let your blood pressure adjust.\n"
                "• **Walking Support**: Family and caregiver notes suggest taking someone's arm or using steady support when walking outside or on uneven ground.\n"
                "• **Hydration**: Ensure you drink a glass of water upon waking up.\n\n"
                "Dr. Ramesh Varma has reviewed this pattern and advises monitoring your morning blood pressure."
            )

        if any(w in q_lower for w in ["doctor", "consultation", "ramesh", "chandran", "visit", "checkup"]):
            return (
                f"Hello {patient_name.split()[0]}.\n\n"
                "Your recent clinical assessments show that your chronic conditions (Type 2 Diabetes, High Blood Pressure, and Knee Osteoarthritis) remain under stable control:\n\n"
                "• **Blood Sugar & Pressure**: Regimen is well-tolerated with stable glycemic numbers.\n"
                "• **Balance Review**: Dr. Ramesh Varma noted morning dizziness and advised gradual positional transitions and blood pressure checks.\n"
                "• **Follow-up**: Please continue your scheduled bimonthly checkups."
            )

        return (
            f"Hello {patient_name.split()[0]}. Your EvoCare health record is active and up to date:\n\n"
            "• **Confirmed Conditions**: Type 2 Diabetes Mellitus, Essential Hypertension, and Bilateral Knee Osteoarthritis.\n"
            "• **Active Regimen**: 4 daily medications managed with your family's pillbox support.\n"
            "• **Caregiver Logs**: Your daily walking, appetite, and sleep are regularly tracked.\n\n"
            "Feel free to ask about your medication times, recent doctor recommendations, or walking tips!"
        )
